spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_crm
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
