server:
  port: 8081

spring:
  application:
    name: trainer-workload-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
  jms:
    listener:
      session:
        transacted: true
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/trainer_workload_db}
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}